# This file is part of AetherLogger
# SPDX-FileCopyrightText: 2024 Rui Oliveira <ruimail24@gmail.com>
# SPDX-License-Identifier: CC0-1.0
repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse-lint-file
